### PR TITLE
Update examples

### PR DESCRIPTION
**Pull request by lovetheidea**
Hi,

Just thought id let you know that you documentation doesn't seem to match what you have in libs.

CheckVATNumber requires you to pass two parameters in your example below: 

"if (checkVATNumber (myVATNumber)) 
      alert ("VAT number has a valid format")
  else 
      alert ("VAT number has invalid format");
"

checkVATNumber returns an object not a true of false value. `checkVATForGivenCountryCode` function does not exist too.

Stripped down the versions, to just the most recent.

Last thing, the .trim() function is not supported in IE8. Replaced with replace.  
http://stackoverflow.com/questions/2308134/trim-in-javascript-not-working-in-ie

### CODE REVIEW

**Comment by jbilcke** [comment]
I indeed iterated a few times on the lib to change the behaviour of the main function, I was a bit in a hurry and did not properly update the documentation.

Thank you Jason!

**Comment by jbilcke** [comment]
Please note: the original function from the original author was more generic and only checked the validity of a number in itself.

I made the change for my own use case, since I did not expect other people to use it soon.

So now I think I will update the function to make it more flexible (eg. with optional country validation).

**Comment by lovetheidea** [comment]
Nice. Great bit of code, saved me a load of time writing it all from scratch ! 

Thanks.

**Comment by jbilcke** [comment]
Glad to hear it! 

I made some fixes and updated the doc

**Pull request merged**
